routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Articles\Http\Controllers\CategoryController;
use Articles\Http\Controllers\ArticlesController;
use Articles\Http\Controllers\SettingsController;
use Articles\Models\Settings;



Route::middleware('web')->group(function (){
    Route::middleware('auth_pacage')->group(function () {
        Route::group(['prefix'=>"admin", 'as'=>'admin.', 'middleware' => 'is_admin'],static function(){
            Route::resource('articles', ArticlesController::class);

            Route::group(['prefix' => 'articles', 'as' => 'articles.'], static function(){
                Route::post('remove_image/{articles}',[ArticlesController::class,'removeImage']);
                Route::resource('category', CategoryController::class);
                Route::resource('settings', SettingsController::class);
            });
        });
    });
    try {
        $settings = Settings::find(1);
        Route::get('/'.$settings->url,[ArticlesController::class,'frontIndex'])->name('articles');
        Route::get('/'.$settings->url . '/{url}',[ArticlesController::class,'articles'])->name('articles.articles');
    } catch (Exception $exception) {
        //throw $th;
    }
});

resources/views/articles/category.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::category />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.articles.index")}}">Статьи</a></li>
            <li class="breadcrumb-item active" aria-current="page">Категории статей</li>
        </ol>
    </div>
@endsection

resources/views/articles/create.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::create :links="$linksContent" />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.articles.index")}}">Статьи</a></li>
            <li class="breadcrumb-item active" aria-current="page">Создание статьи</li>
        </ol>
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::edit :links="$linksContent" :article="$article" />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.articles.index")}}">Статьи</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать</li>
        </ol>
    </div>
@endsection

resources/views/articles/front/articles.blade.php
{{-- @dd($news) --}}
@extends('layouts.inner')
@section('title',$article->seoTitle)
@section('description',$article->seoDescription)
@section('keywords',$article->seoKeywords)
@section('page',true)
@section('content')
<div class="content">

    <x-articles::front.item :article="$article" />
</div>

@endsection

resources/views/articles/front/index.blade.php
@extends('layouts.inner')
@section('title',$settings->seoTitle ?? $settings->title)
@section('description',$settings->seoDescription)
@section('keywords',$settings->seoKeywords)
@section('page',true)
@section('content')
<div class="content">
    {{-- <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" /> --}}
    {{-- <h2>{{ $title }}</h2> --}}

    <x-articles::front.category :articles="$articles" :settings="$settings"/>
</div>

@endsection

resources/views/articles/index.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />

                <x-articles::articles />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Статьи</li>
        </ol>
    </div>
@endsection

resources/views/articles/settings.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::settings />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.articles.index")}}">Статьи</a></li>
            <li class="breadcrumb-item active" aria-current="page">Настройки</li>
        </ol>
    </div>
@endsection